### PR TITLE
inetd mode fix

### LINKED ISSUE #75: inetd mode is broken
Whenever `nbd-server` is launched in inetd mode (passing 0 as the port on the command line), it immediately exits, after sending these two messages to syslog:
```
getsockname failed: Bad file descriptor
Failed to set peername
```

I managed to make it work by applying this patch (against 3.17):

```diff
--- nbd-3.17/nbd-server.c
+++ nbd-3.17/nbd-server.c
@@ -3538,19 +3538,6 @@ int main(int argc, char *argv[]) {
 
        if(serve) {
                g_array_append_val(servers, *serve);
-
-               if(strcmp(genconf.modernport, "0")==0) {
-#ifndef ISSERVER
-                       err("inetd mode requires syslog");
-#endif
-                       CLIENT* client = g_malloc(sizeof(CLIENT));
-                       client->net = -1;
-                       if(!commit_client(client, serve)) {
-                               exit(EXIT_FAILURE);
-                       }
-                       mainloop_threaded(client);
-                       return 0;
-               }
        }
     
        if(!servers || !servers->len) {
@@ -3594,5 +3581,18 @@ int main(int argc, char *argv[]) {
 #endif
                                        ));
 #endif
+
+       if(strcmp(genconf.modernport, "0")==0) {
+#ifndef ISSERVER
+               err("inetd mode requires syslog");
+#endif
+               CLIENT* client = negotiate(0, servers, &genconf);
+               if(!client) {
+                       exit(EXIT_FAILURE);
+               }
+               mainloop_threaded(client);
+               return 0;
+       }
+
        serveloop(servers, &genconf);
 }
```

But I feel this patch may be too heavy-handed, so I'm not submitting it as a pull request.

### PR DESCRIPTION
**Pull request by fstirlitz**
This series of patches restores proper functioning of the inetd mode in `nbd-server`. It also adds inetd mode testing to the test suite. Merging it will resolve #75.

Implementing the latter part required some fairly invasive refactoring of the test client. The testing functions are no longer involved with establishing the transport socket connection; they are handed the socket file descriptor already set up, although they still need to perform NBD protocol negotiation. The name of the protocol-negotiating function was kept as `setup_connection_common`, although it is no longer called from the `setup_*_connection` family of functions.

### CODE REVIEW

File: tests/run/nbd-tester-client.c [hunk 1]
```diff
@@ -1743,6 +1772,8 @@ int main(int argc, char **argv)
 		case 'f':
 			testflags |= TEST_FLUSH;
 			break;
+		case 'I':
+			goto inetd_mode;
```
Comment (yoe) [inline tests/run/nbd-tester-client.c]: This is not at all guaranteed to work.

some getopt() implementations parse the whole command line first, and/or rearrange options so that non-option arguments end up at the very end of the command line. Doing a goto to skip the rest of the command line is not a good idea in that context.

I would prefer it if instead the -I option would set a flag in the `testflags` thing (or flip a boolean somewhere else), and that the command be specified after a double-dash separator; this is documented to be "the end of options", and therefore does not have these issues.

(besides, this kind of use of goto makes things look a bit hairy)

File: tests/run/simple_test [hunk 2]
```diff
@@ -24,8 +24,6 @@ cleanup() {
 		if [ ! -z "$PID" ]
 		then
 			kill $PID || true
-		else
-			echo "E: Could not clean up!"
```
Comment (yoe) [inline tests/run/simple_test]: what's the reason for this one?

**Comment by yoe** [comment]
On Tue, Apr 03, 2018 at 02:22:11PM +0000, Felix S. wrote:
> @fstirlitz commented on this pull request.
> 
> ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
> 
> In tests/run/simple_test:
> 
> > @@ -24,8 +24,6 @@ cleanup() {
>                 if [ ! -z "$PID" ]
>                 then
>                         kill $PID || true
> -               else
> -                       echo "E: Could not clean up!"
> 
> Testing in inetd mode has nbd-tester-client spawn nbd-server on its own,
> instead of having it launched by the shell. The former doesn't return the
> latter's PID back to the testing script, so there's nothing to set the PID
> variable to, and the script would otherwise complain here.

Ah, yes, of course; didn't think of that.

> I guess theoretically if the script could somehow open a socket pair, it could
> then pass appropriate file descriptors to nbd-tester-client and nbd-server and
> obtain a PID of the latter, but I don't see any way to accomplish this
> portably.

Nah, not worth it. I suppose refactoring the script could work, but meh.

-- 
Could you people please use IRC like normal people?!?

  -- Amaya Rodrigo Sastre, trying to quiet down the buzz in the DebConf 2008
     Hacklab

**Comment by yoe** [comment]
On Tue, Apr 03, 2018 at 02:44:24PM +0000, Felix S. wrote:
> @fstirlitz commented on this pull request.
> 
> ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
> 
> In tests/run/nbd-tester-client.c:
> 
> > @@ -1743,6 +1772,8 @@ int main(int argc, char **argv)
>                 case 'f':
>                         testflags |= TEST_FLUSH;
>                         break;
> +               case 'I':
> +                       goto inetd_mode;
> 
> I'm pretty sure this is a violation of the POSIX standard. (And the C standard
> as well: the argv argument to getopt is a char *const [].) Of course, standard
> violations do happen in the real world, but it seems to work fine anyway with
> GNU's version of getopt, which indeed does such a thing. I guess I can change
> it, though.

Thanks.

> (As for hairyness, it's not like it wasn't hairy before. See previous commit.)

Well, yeah, but that doesn't mean we should make it worse :-)

-- 
Could you people please use IRC like normal people?!?

  -- Amaya Rodrigo Sastre, trying to quiet down the buzz in the DebConf 2008
     Hacklab

**Comment by fstirlitz** [comment]
Might as well cherry-pick my latest commit which handles `execvp` failure.
